import React from "react";
export const Data = [
  {
    projectName: "test Project",
    description: "xyz....",
    startDate: "4/8/2022",
    image:
      "https://blog.hyperiondev.com/wp-content/uploads/2018/09/Blog-Article-MERN-Stack.jpg",
    techStacks: ["React", "Next Js", "Node Js", "Express"],
    githubRepo: "",
    liveUrl: "",
    isArchived: false,
    isCompleted: false,
    id:1,
    craetedAt:new Date(),
  },
  {
    projectName: "test Project 1",
    description: "xyz....",
    startDate: "4/8/2022",
    image:
      "https://blog.hyperiondev.com/wp-content/uploads/2018/09/Blog-Article-MERN-Stack.jpg",
    techStacks: ["React", "Next Js", "Node Js", "Express"],
    githubRepo: "",
    liveUrl: "",
    isArchived: false,
    isCompleted: false,
    id:2,
    craetedAt:new Date(),
  },
  {
    projectName: "test Project 2",
    description: "xyz....",
    startDate: "4/8/2022",
    image:
      "https://blog.hyperiondev.com/wp-content/uploads/2018/09/Blog-Article-MERN-Stack.jpg",
    techStacks: ["React", "Next Js", "Node Js", "Express"],
    githubRepo: "",
    liveUrl: "",
    isArchived: false,
    isCompleted: false,
    id:3,
    craetedAt:new Date(),
  },
  {
    projectName: "test Project 3",
    description: "xyz....",
    startDate: "4/8/2022",
    image:
      "https://blog.hyperiondev.com/wp-content/uploads/2018/09/Blog-Article-MERN-Stack.jpg",
    techStacks: ["React", "Next Js", "Node Js", "Express"],
    githubRepo: "",
    liveUrl: "",
    isArchived: false,
    isCompleted: false,
    id:4,
    craetedAt:new Date(),
  },
  {
    projectName: "test Project 4",
    description: "xyz....",
    startDate: "4/8/2022",
    image:
      "https://blog.hyperiondev.com/wp-content/uploads/2018/09/Blog-Article-MERN-Stack.jpg",
    techStacks: ["React", "Next Js", "Node Js", "Express"],
    githubRepo: "",
    liveUrl: "",
    isArchived: false,
    isCompleted: false
    ,
    id:5,
    craetedAt:new Date(),
  },
  {
    projectName: "test Project 5",
    description: "xyz....",
    startDate: "4/8/2022",
    image:
      "https://blog.hyperiondev.com/wp-content/uploads/2018/09/Blog-Article-MERN-Stack.jpg",
    techStacks: ["React", "Next Js", "Node Js", "Express"],
    githubRepo: "",
    liveUrl: "",
    isArchived: false,
    isCompleted: false,
    
    id:6,
    craetedAt:new Date(),
  },
  {
    projectName: "test Project 6",
    description: "xyz....",
    startDate: "4/8/2022",
    image:
      "https://blog.hyperiondev.com/wp-content/uploads/2018/09/Blog-Article-MERN-Stack.jpg",
    techStacks: ["React", "Next Js", "Node Js", "Express"],
    githubRepo: "",
    liveUrl: "",
    isArchived: false,
    isCompleted: false,
    id:7,
    craetedAt:new Date(),
  },
  {
    projectName: "test Project 7",
    description: "xyz....",
    startDate: "4/8/2022",
    image:
      "https://blog.hyperiondev.com/wp-content/uploads/2018/09/Blog-Article-MERN-Stack.jpg",
    techStacks: ["React", "Next Js", "Node Js", "Express"],
    githubRepo: "",
    liveUrl: "",
    isArchived: false,
    isCompleted: false,
    id:8,
    craetedAt:new Date(),
  },
  {
    projectName: "test Project 8",
    description: "xyz....",
    startDate: "4/8/2022",
    image:
      "https://blog.hyperiondev.com/wp-content/uploads/2018/09/Blog-Article-MERN-Stack.jpg",
    techStacks: ["React", "Next Js", "Node Js", "Express"],
    githubRepo: "",
    liveUrl: "",
    isArchived: false,
    isCompleted: false,
    id:9,
    craetedAt:new Date(),
  },
  {
    projectName: "test Project 9",
    description: "xyz....",
    startDate: "4/8/2022",
    image:
      "https://blog.hyperiondev.com/wp-content/uploads/2018/09/Blog-Article-MERN-Stack.jpg",
    techStacks: ["React", "Next Js", "Node Js", "Express"],
    githubRepo: "",
    liveUrl: "",
    isArchived: false,
    isCompleted: false,
    id:10,
    craetedAt:new Date(),
  },
];
export const StackOption = [
  { value: 'React', label: "React" },
  { value: 'Node Js', label: "Node Js" },
  { value: 'C#', label: "C#" },
];
